Repository openjverein/jverein, pull requests merged in 2023-12, with the labels that each got.

#93 Add IBAN to CSVBuchungsImport
  src/de/jost_net/JVerein/Variable/BuchungVar.java
  src/de/jost_net/JVerein/io/CSVBuchungsImport.java
Labels: enhancement

#94 Extend form fields for Spendenbescheinigung
  src/de/jost_net/JVerein/Variable/SpendenbescheinigungVar.java
  src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Labels: enhancement

#96 Do not run nightly build on closed pull requests
  .github/workflows/nightly-builds.yml
Labels: fix

#95 Einstellungen für IBAN, BIC und Gläubiger-ID
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
  src/de/jost_net/JVerein/server/EinstellungImpl.java
Labels: documentation
