Repository openjverein/jverein, pull requests merged in 2024-09, with the labels that each got.

#310 Anleitung für IntelliJ
  .gitignore
  CONTRIBUTING.md
Labels: documentation

#253 Negative zusatzbeitraege zulassen
  src/de/jost_net/JVerein/server/ZusatzbetragImpl.java
Labels: enhancement

#325 Set plugin version in plugin.xml instead off RELEASE file
  .github/workflows/nightly-builds.yml
  build/RELEASE
  build/build.properties
  build/build.xml
  plugin.xml
Labels: fix

#224 DSGVO konformes Löschen von Mitgliedern, implementiert #213
  src/de/jost_net/JVerein/gui/action/MitgliedDeleteAction.java
  src/de/jost_net/JVerein/gui/action/NichtMitgliedDeleteAction.java
  src/de/jost_net/JVerein/server/BuchungImpl.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0443.java
  src/de/jost_net/JVerein/server/MitgliedImpl.java
  src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Labels: enhancement, question
