Repository openjverein/jverein, pull requests merged in 2024-02, with the labels that each got.

#134 Umsatzsteueroption
  .classpath
  src/de/jost_net/JVerein/Variable/MitgliedskontoMap.java
  src/de/jost_net/JVerein/Variable/MitgliedskontoVar.java
  src/de/jost_net/JVerein/gui/action/FormularAnzeigeAction.java
  src/de/jost_net/JVerein/gui/control/AbrechnungslaufBuchungenControl.java
  src/de/jost_net/JVerein/gui/control/AbrechnungslaufControl.java
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
  src/de/jost_net/JVerein/gui/view/EinstellungenBuchfuehrungView.java
  src/de/jost_net/JVerein/io/AbrechnungSEPA.java
  src/de/jost_net/JVerein/io/AbrechnungslaufPDF.java
  src/de/jost_net/JVerein/io/FormularAufbereitung.java
  src/de/jost_net/JVerein/rmi/Einstellung.java
  src/de/jost_net/JVerein/rmi/Mitgliedskonto.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0429.java
  src/de/jost_net/JVerein/server/EinstellungImpl.java
  src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
Labels: documentation, enhancement

#140 Fix Sort und Formatierung für Buchungsart Input
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/dialogs/BuchungsartZuordnungDialog.java
  src/de/jost_net/JVerein/gui/input/BuchungsartInput.java
  src/de/jost_net/JVerein/gui/input/BuchungsartSearchInput.java
Labels: fix

#157 Update list.png
  src/img/list.png
Labels: enhancement

#158 Fix Spendenbescheinigung Anzeige
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
Labels: fix

#161 Verbesserung SpendenbescheinigungAutoNeuView
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungAutoNeuControl.java
  src/de/jost_net/JVerein/gui/view/SpendenbescheinigungAutoNeuView.java
  src/de/jost_net/JVerein/server/SpendenbescheinigungNode.java
Labels: fix

#164 Fix Buchung speichern
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedskontoAuswahlDialog.java
  src/de/jost_net/JVerein/gui/input/MitgliedskontoauswahlInput.java
Labels: fix

#165 Fix Jahresabschluss
  src/de/jost_net/JVerein/server/KontoImpl.java
  src/de/jost_net/JVerein/util/Geschaeftsjahr.java
Labels: fix

#160 Fix Spendenbescheinigung Auto Create
  src/de/jost_net/JVerein/Queries/SpendenbescheinigungBuchungQuery.java
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungAction.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
  src/de/jost_net/JVerein/gui/menu/MitgliedMenu.java
  src/de/jost_net/JVerein/gui/menu/MitgliedskontoMenu.java
  src/de/jost_net/JVerein/gui/view/SpendenbescheinigungListeView.java
  src/de/jost_net/JVerein/gui/view/SpendenbescheinigungView.java
Labels: help wanted, fix

#169 Update BuchungMitgliedskontoZuordnungAction.java
  src/de/jost_net/JVerein/gui/action/BuchungMitgliedskontoZuordnungAction.java
Labels: enhancement
