Repository openjverein/jverein, pull requests merged in 2024-11, with the labels that each got.

#414 Disable Vollzahler auch wenn Beitragsgruppe null ist
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
Labels: fix

#416 Spalte S bei Buchung H,G,S statt nur S
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
Labels: enhancement

#417 Lastschrift Detail View
  src/de/jost_net/JVerein/gui/action/LastschriftDetailAction.java
  src/de/jost_net/JVerein/gui/action/MitgliedDetailAction.java
  src/de/jost_net/JVerein/gui/control/LastschriftControl.java
  src/de/jost_net/JVerein/gui/menu/LastschriftMenu.java
  src/de/jost_net/JVerein/gui/view/LastschriftDetailView.java
  src/de/jost_net/JVerein/io/AbrechnungSEPA.java
Labels: enhancement

#425 Abbrechen bei Mailversand ermöglichen
  src/de/jost_net/JVerein/gui/control/MailControl.java
  src/de/jost_net/JVerein/gui/control/PreNotificationControl.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
  src/de/jost_net/JVerein/io/ZipMailer.java
Labels: enhancement

#424 VCard auch ohne Geschlecht
  src/de/jost_net/JVerein/io/VCardTool.java
Labels: fix

#444 Mitglied Map bei Spendenbescheinigung
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungPrintAction.java
  src/de/jost_net/JVerein/gui/control/FormularfeldControl.java
Labels: enhancement

#431 Spendenbescheinigung auch für abgeschlossene Jahre
  src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Labels: enhancement

#433 Fix SteuerBuchungsart setzen
  src/de/jost_net/JVerein/server/BuchungsartImpl.java
Labels: fix

#449 Fix Buchungsart Steuer Long statt Int
  src/de/jost_net/JVerein/gui/control/BuchungsartControl.java
  src/de/jost_net/JVerein/io/KontenrahmenImportXML.java
  src/de/jost_net/JVerein/io/KontenrahmenImportXMLv2.java
  src/de/jost_net/JVerein/rmi/Buchungsart.java
  src/de/jost_net/JVerein/server/BuchungsartImpl.java
Labels: fix

#464 Update Docu Links
  src/de/jost_net/JVerein/gui/view/DokumentationUtil.java
  src/de/jost_net/JVerein/gui/view/EinstellungenAbrechnungView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenAllgemeinView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenAnzeigeView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenBuchfuehrungView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenDateinamenView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenMailView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenMitgliedAnsichtView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenMitgliederSpaltenView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenRechnungenView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenSpendenbescheinigungenView.java
  src/de/jost_net/JVerein/gui/view/EinstellungenStatistikView.java
Labels: documentation

#430 Aus Buchungsliste zu Mitglied springen
  src/de/jost_net/JVerein/gui/action/MitgliedDetailAction.java
  src/de/jost_net/JVerein/gui/menu/BuchungMenu.java
Labels: enhancement

#476 Rechnungen Löschen in DB Bereinigung
  src/de/jost_net/JVerein/gui/control/DbBereinigenControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
  src/de/jost_net/JVerein/gui/view/DbBereinigenView.java
  src/de/jost_net/JVerein/server/BuchungImpl.java
  src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
Labels: enhancement

#478 Spendenbescheinigung verschluesseln
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungPrintAction.java
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
  src/de/jost_net/JVerein/io/FormularAufbereitung.java
  src/de/jost_net/JVerein/io/Reporter.java
Labels: enhancement

#485 Fix Buchung Filter
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
Labels: fix

#484 Fix Mitglieder Sortierung
  src/de/jost_net/JVerein/Queries/MitgliedQuery.java
Labels: fix

#486 Prüfen ob Mandatsdatum in der Zukunft liegt
  src/de/jost_net/JVerein/server/MitgliedImpl.java
Labels: enhancement

#474 Buchungen mit Spendenbescheinigung nicht editierbar
  src/de/jost_net/JVerein/gui/action/BuchungBuchungsartZuordnungAction.java
  src/de/jost_net/JVerein/gui/action/BuchungDeleteAction.java
  src/de/jost_net/JVerein/gui/action/BuchungKontoauszugZuordnungAction.java
  src/de/jost_net/JVerein/gui/action/BuchungProjektZuordnungAction.java
  src/de/jost_net/JVerein/gui/action/SplitBuchungAction.java
  src/de/jost_net/JVerein/gui/action/SplitbuchungBulkAufloesenAction.java
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
Labels: enhancement

#477 Check bei Setzen der Buchungsart
  src/de/jost_net/JVerein/gui/action/BuchungBuchungsartZuordnungAction.java
  src/de/jost_net/JVerein/server/BuchungImpl.java
Labels: enhancement

#445 Abweichenden Zahlungsweg bei Zusatzbeträgen
  src/de/jost_net/JVerein/gui/action/ZusatzbetragVorlageAuswahlAction.java
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
  src/de/jost_net/JVerein/gui/control/ZusatzbetragControl.java
  src/de/jost_net/JVerein/gui/control/ZusatzbetragVorlageControl.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedZusatzbetragZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ZusatzbetragVorlageDialog.java
  src/de/jost_net/JVerein/gui/parts/ZusatzbetragPart.java
  src/de/jost_net/JVerein/io/AbrechnungSEPA.java
  src/de/jost_net/JVerein/keys/Zahlungsweg.java
  src/de/jost_net/JVerein/rmi/Zusatzbetrag.java
  src/de/jost_net/JVerein/rmi/ZusatzbetragVorlage.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0451.java
  src/de/jost_net/JVerein/server/ZusatzbetragImpl.java
  src/de/jost_net/JVerein/server/ZusatzbetragVorlageImpl.java
Labels: enhancement

#497 behebt SQLException bei Sollbuchungen
  src/de/jost_net/JVerein/Queries/SollbuchungQuery.java
Labels: fix
