Repository openjverein/jverein, pull requests merged in 2024-07, with the labels that each got.

#251 Mitgliedsuche auch Sekundaere Beitragsgruppe finden
  src/de/jost_net/JVerein/Queries/MitgliedQuery.java
Labels: enhancement

#235 Filter für Mail View
  src/de/jost_net/JVerein/gui/control/FilterControl.java
  src/de/jost_net/JVerein/gui/control/MailControl.java
  src/de/jost_net/JVerein/gui/view/MailUebersichtView.java
Labels: enhancement

#262 Building/update
  .github/workflows/nightly-builds.yml
  .github/workflows/release.yml
Labels: fix

#263 Fix ZusatzbeitraegeAction und Icon Update
  src/de/jost_net/JVerein/gui/action/ZusatzbetraegeAction.java
  src/de/jost_net/JVerein/gui/dialogs/ZusatzfelderAuswahlDialog.java
  src/de/jost_net/JVerein/gui/view/FelddefinitionDetailView.java
Labels: fix

#250 Reset Filter für Buchungen View
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/view/BuchungslisteView.java
Labels: enhancement

#234 Filter für Kursteilnehmer View Update
  src/de/jost_net/JVerein/gui/control/KursteilnehmerControl.java
  src/de/jost_net/JVerein/gui/view/AuswertungKursteilnehmerView.java
  src/de/jost_net/JVerein/gui/view/KursteilnehmerSucheView.java
Labels: enhancement

#264 Fix: Mandatsdatum und Geburtsdatum bei Kursteilnehmern
  src/de/jost_net/JVerein/gui/control/KursteilnehmerControl.java
Labels: fix

#239 Feature Lastschrift View
  src/de/jost_net/JVerein/gui/action/LastschriftDeleteAction.java
  src/de/jost_net/JVerein/gui/action/LastschriftListAction.java
  src/de/jost_net/JVerein/gui/control/FilterControl.java
  src/de/jost_net/JVerein/gui/control/LastschriftControl.java
  src/de/jost_net/JVerein/gui/menu/LastschriftMenu.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/view/DokumentationUtil.java
  src/de/jost_net/JVerein/gui/view/LastschriftListeView.java
  src/de/jost_net/JVerein/server/LastschriftImpl.java
Labels: enhancement

#225 Feature alte Buchungen löschen
  src/de/jost_net/JVerein/gui/action/DbBereinigenAction.java
  src/de/jost_net/JVerein/gui/control/DbBereinigenControl.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/view/DbBereinigenView.java
  src/de/jost_net/JVerein/gui/view/DokumentationUtil.java
  src/de/jost_net/JVerein/server/BuchungImpl.java
  src/de/jost_net/JVerein/server/DDLTool/AbstractDDLUpdate.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0441.java
Labels: enhancement

#266 Fix Mailfilter
  src/de/jost_net/JVerein/gui/control/MailControl.java
Labels: fix

#269 Cache für Buchungen
  src/de/jost_net/JVerein/server/BuchungImpl.java
  src/de/jost_net/JVerein/server/LastschriftImpl.java
  src/de/jost_net/JVerein/server/MailEmpfaengerImpl.java
  src/de/jost_net/JVerein/server/MitgliedImpl.java
  src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
  src/de/jost_net/JVerein/server/ZusatzbetragImpl.java
Labels: enhancement

#257 Möglicher Fehler bei Familienzahler
  src/de/jost_net/JVerein/server/MitgliedImpl.java
Labels: documentation, question, fix
