Repository openjverein/jverein, pull requests merged in 2024-03, with the labels that each got.

#188 Fix Mitglied speichern
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/server/MitgliedImpl.java
Labels: fix

#189 Fix Adresse erzeugen
  src/de/jost_net/JVerein/gui/action/AdresseDetailAction.java
Labels: fix

#190 Gespeicherte Mail öffnen ging nicht
  src/de/jost_net/JVerein/gui/action/MailDetailAction.java
Labels: fix

#186 Success message for PDF Spendenbescheinigung
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungPrintAction.java
Labels: enhancement

#180 Feature kontensaldo
  src/de/jost_net/JVerein/gui/action/KontensaldoAction.java
  src/de/jost_net/JVerein/gui/control/JahresabschlussControl.java
  src/de/jost_net/JVerein/gui/control/KontensaldoControl.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/parts/KontensaldoList.java
  src/de/jost_net/JVerein/gui/view/KontensaldoView.java
  src/de/jost_net/JVerein/gui/view/ProjektSaldoView.java
  src/de/jost_net/JVerein/io/SaldoZeile.java
  src/de/jost_net/JVerein/rmi/Konto.java
  src/de/jost_net/JVerein/server/KontoImpl.java
Labels: documentation, enhancement

#187 Set versand to fix error message
  src/de/jost_net/JVerein/gui/control/MailControl.java
Labels: fix

#193 Fix Arbeitseinsätze prüfen
  src/de/jost_net/JVerein/gui/parts/ArbeitseinsatzUeberpruefungList.java
Labels: fix

#197 Fix PseudoIterator.asList() Nullpointer Exception
  src/com/schlevoigt/JVerein/Queries/BuchungsKorrekturQuery.java
  src/de/jost_net/JVerein/Queries/BuchungQuery.java
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/control/BuchungsartControl.java
  src/de/jost_net/JVerein/gui/control/EigenschaftControl.java
  src/de/jost_net/JVerein/gui/control/LehrgangControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/gui/control/MitgliedNextBGruppeControl.java
  src/de/jost_net/JVerein/gui/control/QIFBuchungsartZuordnenControl.java
  src/de/jost_net/JVerein/gui/control/QIFMitgliedZuordnenControl.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungAutoNeuControl.java
  src/de/jost_net/JVerein/gui/dialogs/BuchungsartZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ProjektAuswahlDialog.java
  src/de/jost_net/JVerein/gui/input/BuchungsartInput.java
  src/de/jost_net/JVerein/gui/input/BuchungsartSearchInput.java
  src/de/jost_net/JVerein/gui/input/FormularInput.java
  src/de/jost_net/JVerein/gui/input/JVereinKontoInput.java
  src/de/jost_net/JVerein/gui/input/QIFExternKontenInput.java
  src/de/jost_net/JVerein/gui/parts/KontoList.java
  src/de/jost_net/JVerein/io/SaldoZeile.java
Labels: fix

#199 Fix MitgliedskontoMenü Exception
  src/de/jost_net/JVerein/gui/menu/MitgliedskontoMenu.java
Labels: fix

#200 Korrigiere Umbenennung und Typo
  src/de/jost_net/JVerein/gui/action/MitgliedskontoIstbuchungLoesenAction.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
  src/de/jost_net/JVerein/gui/menu/MitgliedskontoMenu.java
Labels: fix
