Repository openjverein/jverein, pull requests merged in 2024-01, with the labels that each got.

#111 Schöne Icons für KontoAuswahlDialog
  src/de/jost_net/JVerein/gui/dialogs/BuchungenMitgliedskontenZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/KontoAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/KontoauszugZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedskontoAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ProjektAuswahlDialog.java
Labels: enhancement

#97 Update markdown info
  CONTRIBUTING.md
  README.md
Labels: documentation

#114 Button Korrektur für alle Dialoge
  src/de/jost_net/JVerein/gui/dialogs/BuchungenMitgliedskontenZuordnungVorschauDialog.java
  src/de/jost_net/JVerein/gui/dialogs/BuchungsjournalSortDialog.java
  src/de/jost_net/JVerein/gui/dialogs/DokumentDialog.java
  src/de/jost_net/JVerein/gui/dialogs/EigenschaftenAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ExportDialog.java
  src/de/jost_net/JVerein/gui/dialogs/FamilienmitgliedEntfernenDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ImportDialog.java
  src/de/jost_net/JVerein/gui/dialogs/KontoauszugZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MailEmpfaengerAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MailVorlagenAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MailVorschauDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedArbeitseinsatzZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedZusatzbetragZuordnungDialog.java
  src/de/jost_net/JVerein/gui/dialogs/MitgliedskontoAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/PersonenartDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ProjektAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/QRCodeImageDialog.java
  src/de/jost_net/JVerein/gui/dialogs/SammelueberweisungAuswahlDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ShowVariablesDialog.java
  src/de/jost_net/JVerein/gui/dialogs/ZusatzbetragVorlageDialog.java
Labels: enhancement

#120 Fix MitgliedZusatzbetraegeZuordnungAction Close Fehler
  src/de/jost_net/JVerein/gui/action/MitgliedZusatzbetraegeZuordnungAction.java
Labels: fix

#118 Fix MailVorlagenAuswahlDialog Close Fehler
  src/de/jost_net/JVerein/gui/action/MailDetailAction.java
  src/de/jost_net/JVerein/gui/dialogs/MailVorlagenAuswahlDialog.java
Labels: fix

#119 Fix MitgliedVCardQRCodeAction ESC Fehler
  src/de/jost_net/JVerein/gui/action/MitgliedVCardQRCodeAction.java
Labels: fix

#123 Fix MitgliedMailSendenAction
  src/de/jost_net/JVerein/gui/action/MitgliedMailSendenAction.java
Labels: fix

#124 Doppelklick auf Dokument zeigt das Dokument an
  src/de/jost_net/JVerein/gui/control/DokumentControl.java
Labels: enhancement

#104 Feature: Unterdrücke Buchungsarten in Dialogen
  src/de/jost_net/JVerein/gui/action/BuchungBuchungsartZuordnungAction.java
  src/de/jost_net/JVerein/gui/control/BuchungsControl.java
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
  src/de/jost_net/JVerein/gui/dialogs/BuchungsartZuordnungDialog.java
  src/de/jost_net/JVerein/gui/input/BuchungsartSearchInput.java
  src/de/jost_net/JVerein/gui/view/EinstellungenBuchfuehrungView.java
  src/de/jost_net/JVerein/rmi/Einstellung.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0426.java
  src/de/jost_net/JVerein/server/EinstellungImpl.java
Labels: enhancement

#122 Feature/buchungskorrektur
  src/com/schlevoigt/JVerein/Queries/BuchungsKorrekturQuery.java
  src/com/schlevoigt/JVerein/gui/action/BuchungsTexteKorrigierenAction.java
  src/com/schlevoigt/JVerein/gui/control/BuchungsTextKorrekturControl.java
  src/com/schlevoigt/JVerein/gui/view/BuchungsTexteKorrigierenView.java
  src/com/schlevoigt/JVerein/util/Misc.java
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/view/EinstellungenBuchfuehrungView.java
  src/de/jost_net/JVerein/io/Buchungsuebernahme.java
  src/de/jost_net/JVerein/rmi/Einstellung.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0427.java
  src/de/jost_net/JVerein/server/EinstellungImpl.java
Labels: enhancement

#135 NEW: Sent E-Mail from SpendenbescheinigungListeView
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungEmailAction.java
  src/de/jost_net/JVerein/gui/menu/SpendenbescheinigungMenu.java
Labels: documentation, enhancement
