Repository openjverein/jverein, pull requests merged in 2024-08, with the labels that each got.

#276 Feature Filter Update
  src/de/jost_net/JVerein/gui/control/AbrechnungslaufControl.java
  src/de/jost_net/JVerein/gui/control/AnfangsbestandControl.java
  src/de/jost_net/JVerein/gui/control/KursteilnehmerControl.java
  src/de/jost_net/JVerein/gui/view/AbrechnungslaufListView.java
  src/de/jost_net/JVerein/gui/view/AbrechnungslaufView.java
  src/de/jost_net/JVerein/gui/view/AnfangsbestandListView.java
  src/de/jost_net/JVerein/gui/view/KursteilnehmerSucheView.java
  src/de/jost_net/JVerein/server/AnfangsbestandImpl.java
Labels: enhancement

#298 Fix Layout der Spendenbescheinigung
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungPrintAction.java
  src/de/jost_net/JVerein/server/SpendenbescheinigungImpl.java
Labels: fix

#290 Feature Prenotification im Navigationsbaum
  src/de/jost_net/JVerein/gui/action/PreNotificationAction.java
  src/de/jost_net/JVerein/gui/control/DruckMailControl.java
  src/de/jost_net/JVerein/gui/control/FilterControl.java
  src/de/jost_net/JVerein/gui/control/LastschriftControl.java
  src/de/jost_net/JVerein/gui/control/PreNotificationControl.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
  src/de/jost_net/JVerein/gui/input/IntegerNullInput.java
  src/de/jost_net/JVerein/gui/menu/LastschriftMenu.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/view/LastschriftListeView.java
  src/de/jost_net/JVerein/gui/view/PreNotificationView.java
  src/de/jost_net/JVerein/io/AbstractMitgliedskontoDokument.java
  src/de/jost_net/JVerein/io/Ct1Ueberweisung.java
  src/de/jost_net/JVerein/io/FreiesFormularAusgabe.java
  src/de/jost_net/JVerein/io/Kontoauszug.java
  src/de/jost_net/JVerein/keys/Ausgabeart.java
Labels: documentation, enhancement

#302 Fix Buchung Duplizieren
  src/de/jost_net/JVerein/gui/action/BuchungDuplizierenAction.java
Labels: fix

#299 Erweiterung Datenbank bereinigen
  src/de/jost_net/JVerein/gui/action/JahresabschlussDeleteAction.java
  src/de/jost_net/JVerein/gui/control/DbBereinigenControl.java
  src/de/jost_net/JVerein/gui/control/JahresabschlussControl.java
  src/de/jost_net/JVerein/gui/view/DbBereinigenView.java
  src/de/jost_net/JVerein/server/JahresabschlussImpl.java
Labels: documentation, enhancement

#305 Fix EMail Settings
  src/de/jost_net/JVerein/gui/control/DruckMailControl.java
Labels: fix

#306 Update/libs
  .classpath
  junit/src/de/jost_net/JVereinJUnit/VCard/VCardTest.java
  lib/csvjdbc-1.0.40.jar
  lib/csvjdbc.jar
  lib/csvjdbc_info.xml
  lib/ez-vcard-0.10.3.jar
  lib/ez-vcard-0.12.1.jar
  lib/ez-vcard_info.xml
  lib/freemarker-2.3.23.jar
  lib/freemarker-2.3.33.jar
  lib/jackson-core-2.17.2.jar
  lib/jackson-core-2.6.1.jar
  lib/javase-3.1.0.jar
  lib/javase-3.5.3.jar
  lib/joda-time-2.12.7.jar
  lib/joda-time-2.3.jar
  lib/joda-time_info.xml
  lib/jollyday-0.4.7.jar
  lib/jollyday-0.5.10.jar
  lib/jollyday_info.xml
  lib/jsoup-1.18.1.jar
  lib/jsoup-1.8.3.jar
  lib/junit-4.13.2.jar
  lib/junit-4.8.1.jar
  lib/junit_info.xml
  lib/snakeyaml-1.13.jar
  lib/snakeyaml-2.2.jar
  lib/vinnie-2.0.1.jar
  lib/vinnie-2.0.2.jar
  src/de/jost_net/JVerein/io/VCardTool.java
Labels: fix
