Repository openjverein/jverein, pull requests merged in 2025-02, with the labels that each got.

#625 Sollbuchung Neu Button. Sollbuchung Menü erweitert
  src/de/jost_net/JVerein/gui/action/RechnungNeuAction.java
  src/de/jost_net/JVerein/gui/action/SollbuchungNeuAction.java
  src/de/jost_net/JVerein/gui/action/SollbuchungRechnungAction.java
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/gui/control/RechnungControl.java
  src/de/jost_net/JVerein/gui/menu/MitgliedskontoMenu.java
  src/de/jost_net/JVerein/gui/view/AbstractMitgliedDetailView.java
  src/de/jost_net/JVerein/gui/view/RechnungMailView.java
  src/de/jost_net/JVerein/gui/view/RechnungView.java
  src/de/jost_net/JVerein/gui/view/SollbuchungListeView.java
Labels: enhancement

#648 Fix Buchungsklassensaldo
  src/de/jost_net/JVerein/gui/parts/BuchungsklasseSaldoList.java
Labels: fix

#409 Mitglieder Suche auch bei Vollzahler
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/gui/input/VollzahlerInput.java
  src/de/jost_net/JVerein/gui/input/VollzahlerSearchInput.java
Labels: enhancement

#666 Fix Spendenbescheinigung Mailversand und Konto Buchungsartauswahl
  plugin.xml
  src/de/jost_net/JVerein/gui/control/KontoControl.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
Labels: fix, blocked

#672 Fix Bugs in Backup und BuchungImpl
  src/de/jost_net/JVerein/gui/action/BackupCreateAction.java
  src/de/jost_net/JVerein/server/BeitragsgruppeImpl.java
  src/de/jost_net/JVerein/server/BuchungImpl.java
  src/de/jost_net/JVerein/server/BuchungsartImpl.java
  src/de/jost_net/JVerein/server/KontoImpl.java
  src/de/jost_net/JVerein/server/ZusatzbetragImpl.java
  src/de/jost_net/JVerein/server/ZusatzbetragVorlageImpl.java
Labels: fix

#682 Fix Altersstaffel
  src/de/jost_net/JVerein/gui/control/BeitragsgruppeControl.java
Labels: fix

#683 Fix Diagnose Backup Import von Sollbuchungen ohne Zahler
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
  src/de/jost_net/JVerein/server/MitgliedskontoImpl.java
Labels: fix

#690 Fix für 687 zu 3.0.x
  src/de/jost_net/JVerein/server/EinstellungImpl.java
Labels: fix

#693 Fix für 687 zu 3.1.x
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0464.java
  src/de/jost_net/JVerein/server/EinstellungImpl.java
Labels: fix

#615 BSH auf v3.0.0-SNAPSHOT 20230205 aktualisiert
  .classpath
  lib/bsh-3.0.0-20230205.094654-3.jar
  lib/bsh-core-2.0b4.jar
Labels: patch

#680 AutoUpdateTablePart auch bei MailControl
  src/de/jost_net/JVerein/gui/control/MailControl.java
  src/de/jost_net/JVerein/gui/parts/AutoUpdateTablePart.java
Labels: enhancement

#677 Jameica und Hibiscus Abhängigkeit im build definieren und bauen
  .github/actions/build-dependencies/action.yml
  .github/workflows/buildcheck.yml
  .github/workflows/nightly-build.yml
  .github/workflows/release.yml
  .github/workflows/reusable-build.yml
  build/build.properties
  build/build.xml
Labels: patch

#697 Individuelle Mandats-ID
  src/de/jost_net/JVerein/gui/control/MitgliedControl.java
  src/de/jost_net/JVerein/keys/SepaMandatIdSource.java
  src/de/jost_net/JVerein/rmi/Mitglied.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0466.java
  src/de/jost_net/JVerein/server/MitgliedImpl.java
Labels: enhancement

#705 Fix GitHub workflow merge master into feature
  .github/workflows/merge-master-into-feature.yml
  .project
Labels: fix

#714 Fix Auswertung Nicht-Mitglied
  src/de/jost_net/JVerein/gui/control/FilterControl.java
Labels: fix

#721 Update zu Fix Auswertung Nichtmitglieder
  src/de/jost_net/JVerein/gui/control/FilterControl.java
  src/de/jost_net/JVerein/gui/view/AuswertungNichtMitgliedView.java
Labels: fix
