Repository openjverein/jverein, pull requests merged in 2025-03, with the labels that each got.

#707 Mittelverwendung Fixes
  src/de/jost_net/JVerein/gui/control/MittelverwendungControl.java
  src/de/jost_net/JVerein/gui/dialogs/MittelverwendungDialog.java
  src/de/jost_net/JVerein/gui/parts/MittelverwendungFlowList.java
  src/de/jost_net/JVerein/keys/Kontoart.java
Labels: fix

#746 Bei Sollbuchung zuordnen auch auf Mitglied prüfen
  src/de/jost_net/JVerein/Queries/SollbuchungQuery.java
Labels: enhancement

#754 Summen Beträge in Summary Zeile bei Kontensaldo View
  src/de/jost_net/JVerein/gui/parts/KontensaldoList.java
  src/de/jost_net/JVerein/gui/parts/KontensaldoListTablePart.java
Labels: enhancement

#752 Fix drop not null in H2DB
  src/de/jost_net/JVerein/server/DDLTool/AbstractDDLUpdate.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0380.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0381.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0382.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0447.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0452.java
Labels: fix

#747 Istbuchung von Sollbuchung lösen in Sollbuchung Detail View
  src/de/jost_net/JVerein/gui/action/IstbuchungLoesenAction.java
  src/de/jost_net/JVerein/gui/control/SollbuchungControl.java
  src/de/jost_net/JVerein/gui/menu/BuchungPartBearbeitenMenu.java
Labels: enhancement

#762 Fix Zahlungswege für Sollbuchungen
  src/de/jost_net/JVerein/gui/action/SollbuchungNeuAction.java
  src/de/jost_net/JVerein/gui/control/MitgliedskontoControl.java
Labels: fix

#776 Fehlerbehandlung und Ausgabe bei Abrechnung
  src/de/jost_net/JVerein/gui/control/AbrechnungSEPAControl.java
  src/de/jost_net/JVerein/gui/control/EinstellungControl.java
Labels: fix

#778 Fix fehlende Allgemeine Map bei Mail Vorlagen
  src/de/jost_net/JVerein/gui/view/MailVorlageDetailView.java
Labels: fix

#742 Buchungsart bei Buchungsübername automatisch bestimmen
  src/de/jost_net/JVerein/gui/action/BuchungsuebernahmeAction.java
  src/de/jost_net/JVerein/gui/control/BuchungsartControl.java
  src/de/jost_net/JVerein/gui/dialogs/BuchungUebernahmeProtokollDialog.java
  src/de/jost_net/JVerein/gui/view/BuchungsartDetailView.java
  src/de/jost_net/JVerein/io/Buchungsuebernahme.java
  src/de/jost_net/JVerein/rmi/Buchungsart.java
  src/de/jost_net/JVerein/server/BuchungsartImpl.java
  src/de/jost_net/JVerein/server/DDLTool/Updates/Update0470.java
Labels: documentation, enhancement

#774 Aus Druck und Mail View Vorlagen erzeugen
  src/de/jost_net/JVerein/gui/action/MailTextVorschauAction.java
  src/de/jost_net/JVerein/gui/action/MailVorlageUebernehmenAction.java
  src/de/jost_net/JVerein/gui/control/DruckMailControl.java
  src/de/jost_net/JVerein/gui/control/IMailControl.java
  src/de/jost_net/JVerein/gui/control/MailControl.java
  src/de/jost_net/JVerein/gui/control/MailVorlageControl.java
  src/de/jost_net/JVerein/gui/dialogs/MailTextVorschauDialog.java
  src/de/jost_net/JVerein/gui/view/FreiesFormularMailView.java
  src/de/jost_net/JVerein/gui/view/KontoauszugMailView.java
  src/de/jost_net/JVerein/gui/view/MahnungMailView.java
  src/de/jost_net/JVerein/gui/view/MailDetailView.java
  src/de/jost_net/JVerein/gui/view/MailVorlageDetailView.java
  src/de/jost_net/JVerein/gui/view/PreNotificationMailView.java
  src/de/jost_net/JVerein/gui/view/RechnungMailView.java
  src/de/jost_net/JVerein/gui/view/SpendenbescheinigungMailView.java
Labels: enhancement

#756 Geldspendenbescheinigung über Buchungsmenü erzeugen
  src/de/jost_net/JVerein/gui/action/SpendenbescheinigungAction.java
  src/de/jost_net/JVerein/gui/control/SpendenbescheinigungControl.java
  src/de/jost_net/JVerein/gui/menu/BuchungMenu.java
Labels: enhancement

#781 Fix fehlendes Mitglied in Spendenbescheinigung bei alternativem
  src/de/jost_net/JVerein/util/SpbAdressaufbereitung.java
Labels: fix

#786 GUI Update für angezeigter Zeitraum
  src/de/jost_net/JVerein/gui/parts/VonBisPart.java
Labels: enhancement

#750 Abhängigkeiten via Maven Artifact Resolver Ant Tasks laden
  .github/actions/build-dependencies/action.yml
  .gitignore
  CONTRIBUTING.md
  build/build.xml
  build/maven-resolver-ant-tasks-1.5.2-uber.jar
  lib.src/super-csv-2.4.0-sources.jar
  lib/activation.jar
  lib/beanshell_info.xml
  lib/bsh-core-2.0b4.jar
  lib/core-3.1.0.jar
  lib/csvjdbc-1.0.40.jar
  lib/dom4j-2.1.4.jar
  lib/ez-vcard-0.12.1.jar
  lib/freemarker-2.3.33.jar
  lib/itext-hyph-xml.jar
  lib/jackson-core-2.17.2.jar
  lib/jakarta.activation-api-2.1.3.jar
  lib/javase-3.5.3.jar
  lib/javax.mail-1.6.2.jar
  lib/joda-time-2.12.7.jar
  lib/jollyday-0.5.10.jar
  lib/jsoup-1.18.1.jar
  lib/junit-4.13.2.jar
  lib/mustang-2.16.0.jar
  lib/snakeyaml-2.2.jar
  lib/vinnie-2.0.2.jar
  lib/xmpbox-3.0.3.jar
  pom.xml
Labels: enhancement

#790 Rechnungsdatum aus Sollbuchung
  src/de/jost_net/JVerein/gui/action/GesamtrechnungNeuAction.java
  src/de/jost_net/JVerein/gui/action/RechnungNeuAction.java
  src/de/jost_net/JVerein/gui/dialogs/RechnungDialog.java
Labels: enhancement

#809 Fix .classpath
  .classpath
Labels: fix

#741 Mittelverwendung Saldo Liste View 2
  src/de/jost_net/JVerein/gui/control/BuchungsklasseSaldoControl.java
  src/de/jost_net/JVerein/gui/navigation/MyExtension.java
  src/de/jost_net/JVerein/gui/parts/AbstractSaldoList.java
  src/de/jost_net/JVerein/gui/parts/BuchungsklasseSaldoList.java
  src/de/jost_net/JVerein/gui/parts/MittelverwendungFlowList.java
  src/de/jost_net/JVerein/gui/parts/MittelverwendungFlowSaldoList.java
  src/de/jost_net/JVerein/gui/view/DokumentationUtil.java
  src/de/jost_net/JVerein/gui/view/MittelverwendungSaldoView.java
  src/de/jost_net/JVerein/io/BuchungsklassesaldoCSV.java
  src/de/jost_net/JVerein/io/BuchungsklassesaldoPDF.java
Labels: enhancement
